/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.example.Cat;

public class CatFactory {
    public static Cat createCat() {
        return new Cat("Richard");
    }
}
